language: php

php:
  - 5.4

env:
  - DB=mysql

before_script:
  - chmod -R 777 ./app/tmp
  - sudo apt-get install lighttpd
  - pear channel-discover pear.cakephp.org
  - pear install --alldeps cakephp/CakePHP_CodeSniffer
  - phpenv rehash
  - set +H

script:
  - sh -c "./lib/Cake/Console/cake test app Controller/LoginWithToken --stderr; fi"

notifications:
  email: false